/* Generated By:JJTree: Do not edit this line. ASTClassBodyDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.parser;

public
class ASTClassBodyDeclaration extends SimpleNode {
  public ASTClassBodyDeclaration(int id) {
    super(id);
  }

  public ASTClassBodyDeclaration(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a2376447d4a6b269ffb213aa465eb48 (do not edit this line) */
