/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.parser;

import java.io.PrintWriter;

public
class ASTIfStatement extends SimpleNode {
  public ASTIfStatement(int id) {
    super(id);
  }

  public ASTIfStatement(JDCParser p, int id) {
    super(p, id);
  }

  public void process(PrintWriter ostr){
    SimpleNode child;
    for (int i = 0; i<jjtGetNumChildren(); i++) {
      child = (SimpleNode) jjtGetChild(i);
      child.process(ostr);
    }

  }
}
/* JavaCC - OriginalChecksum=e4047c468b223627eae64966f96c3139 (do not edit this line) */
