/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.parser;

public class ASTIfStatement extends SimpleNode {
    public ASTIfStatement(int id) {
    super(id);
  }

//  public ASTIfStatement(JDCParser p, int id) {
//    super(p, id);
//  }

    public void process(){


    }
}
/* JavaCC - OriginalChecksum=324204ebf08afeb3868ae5462afee3bf (do not edit this line) */
