/* Generated By:JavaCC: Do not edit this line. JDCParserTreeConstants.java Version 5.0 */
package main.java.parser;

public interface JDCParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTBLOCK = 2;
  public int JJTIFSTATEMENT = 3;
  public int JJTDECAFBLOCK = 4;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Block",
    "IfStatement",
    "DecafBlock",
  };
}
/* JavaCC - OriginalChecksum=9b6a945d4a32402c442bd628e502f2af (do not edit this line) */
