/* Generated By:JavaCC: Do not edit this line. JDCParserTreeConstants.java Version 5.0 */
package main.java.parser;

public interface JDCParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTCLASSBODYDECLARATION = 2;
  public int JJTMETHODDECLARATION = 3;
  public int JJTSTATEMENTEXPRESSION = 4;
  public int JJTIFSTATEMENT = 5;
  public int JJTWHILESTATEMENT = 6;
  public int JJTDOSTATEMENT = 7;
  public int JJTFORSTATEMENT = 8;
  public int JJTDECAFBLOCK = 9;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "ClassBodyDeclaration",
    "MethodDeclaration",
    "StatementExpression",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "DecafBlock",
  };
}
/* JavaCC - OriginalChecksum=a673589d3464b6ab080ebc1626c8d8ee (do not edit this line) */
