/* Generated By:JavaCC: Do not edit this line. JDCParserTreeConstants.java Version 5.0 */
package main.java.parser;

public interface JDCParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTIFSTATEMENT = 2;
  public int JJTDECAFBLOCK = 3;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "IfStatement",
    "DecafBlock",
  };
}
/* JavaCC - OriginalChecksum=203fa3f8479879cd4ddf0db9a4448fb7 (do not edit this line) */
