/* Generated By:JavaCC: Do not edit this line. JDCParserTreeConstants.java Version 5.0 */
package parser;

public interface JDCParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTDECAFBLOCK = 2;
  public int JJTDECAFPRINTLN = 3;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "DecafBlock",
    "DecafPrintln",
  };
}
/* JavaCC - OriginalChecksum=baf0b3a1a46ec2e57979fec8193b9b2a (do not edit this line) */
