/* Generated By:JavaCC: Do not edit this line. JDCParserTreeConstants.java Version 5.0 */
package parser;

public interface JDCParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
  };
}
/* JavaCC - OriginalChecksum=31461405c3de46c37e82de3dc369f49a (do not edit this line) */
