/* Generated By:JavaCC: Do not edit this line. JDCParserTreeConstants.java Version 5.0 */
package parser;

public interface JDCParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTDECAFBLOCK = 2;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "DecafBlock",
  };
}
/* JavaCC - OriginalChecksum=2e6157c31f6fa330a9f7008d7f9d0d55 (do not edit this line) */
