/* Generated By:JJTree: Do not edit this line. ASTArrayRBracket.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

import java.io.PrintWriter;

public
class ASTArrayRBracket extends SimpleNode {
  public ASTArrayRBracket(int id) {
    super(id);
  }

  public ASTArrayRBracket(JDCParser p, int id) {
    super(p, id);
  }

  public void process(PrintWriter ostr) {
    ostr.print("]");
  }
}
/* JavaCC - OriginalChecksum=413545ddcf8fc3b605bad714a9c920f2 (do not edit this line) */
