/* Generated By:JJTree: Do not edit this line. ASTAdditiveOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTAdditiveOperator extends SimpleNode {
  public ASTAdditiveOperator(int id) {
    super(id);
  }

  public ASTAdditiveOperator(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=34817aeca5c21ec9ec8e70741ed60d24 (do not edit this line) */
