/* Generated By:JJTree: Do not edit this line. ASTAllocationExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTAllocationExpression extends SimpleNode {
  public ASTAllocationExpression(int id) {
    super(id);
  }

  public ASTAllocationExpression(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a58fab2bcaa851d841ed90c071f5a484 (do not edit this line) */
