/* Generated By:JJTree: Do not edit this line. ASTAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

import java.io.PrintWriter;

public
class ASTAssignment extends SimpleNode {
  public ASTAssignment(int id) {
    super(id);
  }

  public ASTAssignment(JDCParser p, int id) {
    super(p, id);
  }

  public void process(PrintWriter ostr) {
    /* single equals inside an Assignment node inside a loop condition */
    Token t = begin;

    while (t != null) {
      if (t.image.equals("=") && jjtGetParent() instanceof ConditionalClosingBraceSimpleNode) {
        String warning = "You have used assignment operator \'=\' in a loop condition. \nTo check for equality, use double equals \'==\'.";
        StyleWarnings.generateWarning(t, parser, warning);
      }
      t = t.next;
    }

    super.process(ostr);

  }
}
/* JavaCC - OriginalChecksum=0255dc49f2e135d783b37e044b2be3f3 (do not edit this line) */
