/* Generated By:JJTree: Do not edit this line. ASTArrayInitialiser.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTArrayInitialiser extends SimpleNode implements LastTokenEater{
  public ASTArrayInitialiser(int id) {
    super(id);
  }

  public ASTArrayInitialiser(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8bae14fb72e1dad68521fd9e2a994b1f (do not edit this line) */
