/* Generated By:JJTree: Do not edit this line. ASTArrayDimensions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTArrayDimensions extends SimpleNode {
  public ASTArrayDimensions(int id) {
    super(id);
  }

  public ASTArrayDimensions(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2668670602bd6469721caafffe8aeafc (do not edit this line) */
