/* Generated By:JJTree: Do not edit this line. ASTAssignmentOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTAssignmentOperator extends SimpleNode {
  public ASTAssignmentOperator(int id) {
    super(id);
  }

  public ASTAssignmentOperator(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3a4d6b3648814f6a9252193cbeaa204 (do not edit this line) */
