/* Generated By:JJTree: Do not edit this line. ASTArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTArguments extends SimpleNode implements LastTokenEater {
  public ASTArguments(int id) {
    super(id);
  }

  public ASTArguments(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b9f9defa5ddff0d7ab2dc0552e6ad7e (do not edit this line) */
