/* Generated By:JJTree: Do not edit this line. ASTBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTBlock extends ClosingBraceSimpleNode {
  public ASTBlock(int id) {
    super(id);
  }

  public ASTBlock(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3fa78c8d04b8258428d8a9a1423b7e8 (do not edit this line) */
