/* Generated By:JJTree: Do not edit this line. ASTBreakStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTBreakStatement extends SimpleNode {
  public ASTBreakStatement(int id) {
    super(id);
  }

  public ASTBreakStatement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=74bafe3767fe2bc518fb28a85f1435c4 (do not edit this line) */
