/* Generated By:JJTree: Do not edit this line. ASTBlockStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTBlockStatement extends SimpleNode {
  public ASTBlockStatement(int id) {
    super(id);
  }

  public ASTBlockStatement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b3b73a9564143eec11cd2c93cf9a700 (do not edit this line) */
