/* Generated By:JJTree: Do not edit this line. ASTCastLookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTCastLookahead extends SimpleNode {
  public ASTCastLookahead(int id) {
    super(id);
  }

  public ASTCastLookahead(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49498af90645945e6e8e8a83c771014a (do not edit this line) */
