/* Generated By:JJTree: Do not edit this line. ASTCatch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTCatch extends SimpleNode {
  public ASTCatch(int id) {
    super(id);
  }

  public ASTCatch(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=020ea42a886fddb3b3070f29206ec7d3 (do not edit this line) */
