/* Generated By:JJTree: Do not edit this line. ASTClassBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTClassBody extends SimpleNode {
  public ASTClassBody(int id) {
    super(id);
  }

  public ASTClassBody(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c6941dec9027852c1e09eda9526c0688 (do not edit this line) */
