/* Generated By:JJTree: Do not edit this line. ASTConditionalAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTConditionalAnd extends SimpleNode {
  public ASTConditionalAnd(int id) {
    super(id);
  }

  public ASTConditionalAnd(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dcb35328c3d41e66c0e4fe8115ce739b (do not edit this line) */
