/* Generated By:JJTree: Do not edit this line. ASTCastLookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTCastLookahead extends SimpleNode {
  public ASTCastLookahead(int id) {
    super(id);
  }

  public ASTCastLookahead(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e869f8c6d4dd85049da2ce75b0c8a0e8 (do not edit this line) */
