/* Generated By:JJTree: Do not edit this line. ASTConditionalOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTConditionalOr extends SimpleNode {
  public ASTConditionalOr(int id) {
    super(id);
  }

  public ASTConditionalOr(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02a4590bd4c7cf10863f69c055988b6c (do not edit this line) */
