/* Generated By:JJTree: Do not edit this line. ASTDoStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.JDCParser;

public
class ASTDoStatement extends ClosingBraceSimpleNode {
  public ASTDoStatement(int id) {
    super(id);
  }

  public ASTDoStatement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c54908ddec55352e1e69594cb4a24b6d (do not edit this line) */
