/* Generated By:JJTree: Do not edit this line. ASTDecafClass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

import java.io.PrintWriter;
import static ast.NodeUtils.EOL;

public
class ASTDecafClass extends SimpleNode {
    public ASTDecafClass(int id) {
        super(id);
    }

    public ASTDecafClass(JDCParser p, int id) {
        super(p, id);
        indent = false;
        decafClass = true;
    }

    public void process(PrintWriter ostr) {
	  String TAB = NodeUtils.INDENTATION;
        String classDec = EOL + "import java.util.Scanner;" + EOL + EOL +  //Assign the class/main method encapsulation code
                "public class " + parser.getClassName() + " { " + EOL + TAB +
                "private static Scanner __input = new Scanner(System.in);" + EOL + EOL  + TAB; //init Scanner for reading from stdin

        ostr.print(classDec);
        super.process(ostr);

	  // Add JavaDecaf "read" methods; "print" methods are not added because it is just too much unnecessary
	  // boilerplate (there are 10 polymorphic versions of System.out.println()): it is much simpler and
	  // cleaner to replace printX for System.out.printX in the AST. 
	  String readLine  = EOL + TAB + "public static String readLine()  { return __input.nextLine(); }" + EOL;
	  String readInt   = EOL + TAB + "public static int    readInt()   { return Integer.parseInt(readLine());  }" + EOL;
	  String readDouble= EOL + TAB + "public static double readdouble(){ return Double.parseDouble(readLine());}" + EOL;
	  ostr.print(readLine + readInt + readDouble);

	  ClosingBraceSimpleNode.closeBracket(ostr, indentationLevel);
    }


}
/* JavaCC - OriginalChecksum=ba592f10a30b87d2e827995b8d4e8c28 (do not edit this line) */
