/* Generated By:JJTree: Do not edit this line. ASTDecafMethod.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTDecafMethod extends SimpleNode {
  public ASTDecafMethod(int id) {
    super(id);
  }

  public ASTDecafMethod(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c48b41e1dc3746d0faa1ce23e12828fb (do not edit this line) */
