/* Generated By:JJTree: Do not edit this line. ASTDefaultSwitchLabel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTDefaultSwitchLabel extends SimpleNode implements IndentationContainer, Indentable {
  public ASTDefaultSwitchLabel(int id) {
    super(id);
  }

  public ASTDefaultSwitchLabel(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e74c10a0fba716c3c88eae2195a0667 (do not edit this line) */
