/* Generated By:JJTree: Do not edit this line. ASTElseStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTElseStatement extends SimpleNode {
  public ASTElseStatement(int id) {
    super(id);
  }

  public ASTElseStatement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e451a1fa12c04fa13a3198a5c2bd70c2 (do not edit this line) */
