/* Generated By:JJTree: Do not edit this line. ASTExclusiveOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTExclusiveOrExpression extends SimpleNode {
  public ASTExclusiveOrExpression(int id) {
    super(id);
  }

  public ASTExclusiveOrExpression(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=059f4a6823de18aec47b89cd4ce975b5 (do not edit this line) */
