/* Generated By:JJTree: Do not edit this line. ASTElseIfStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTElseIfStatement extends ConditionalSimpleNode {
  public ASTElseIfStatement(int id) {
    super(id);
  }

  public ASTElseIfStatement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=946ca71f48279af9343c724f9ae6b1e1 (do not edit this line) */
