/* Generated By:JJTree: Do not edit this line. ASTEmptyStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTEmptyStatement extends SimpleNode {
  public ASTEmptyStatement(int id) {
    super(id);
  }

  public ASTEmptyStatement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dd4b63691d862c7dcbe2c14116aea958 (do not edit this line) */
