/* Generated By:JJTree: Do not edit this line. ASTExplicitConstructorInvocation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTExplicitConstructorInvocation extends SimpleNode {
  public ASTExplicitConstructorInvocation(int id) {
    super(id);
  }

  public ASTExplicitConstructorInvocation(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6a6f78fc01d4ad00f0f4f459d411958b (do not edit this line) */
