/* Generated By:JJTree: Do not edit this line. ASTEqualityOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTEqualityOperator extends SimpleNode {
  public ASTEqualityOperator(int id) {
    super(id);
  }

  public ASTEqualityOperator(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e24454954bbc15803fc5d26d70110192 (do not edit this line) */
