/* Generated By:JJTree: Do not edit this line. ASTFormalParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTFormalParameters extends SimpleNode {
  public ASTFormalParameters(int id) {
    super(id);
  }

  public ASTFormalParameters(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c716d12872ba51618e1bdc56693d6c4 (do not edit this line) */
