/* Generated By:JJTree: Do not edit this line. ASTForStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.JDCParser;

public
class ASTForStatement extends ConditionalSimpleNode {
  public ASTForStatement(int id) {
    super(id);
  }

  public ASTForStatement(JDCParser p, int id) {
    super(p, id);
  }


}
/* JavaCC - OriginalChecksum=df789b60d21ef1f59f924b174a3b0d59 (do not edit this line) */
