/* Generated By:JJTree: Do not edit this line. ASTForUpdate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTForUpdate extends SimpleNode {
  public ASTForUpdate(int id) {
    super(id);
  }

  public ASTForUpdate(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a2aa49ad0d35ddf7ccea6da61374fd4 (do not edit this line) */
