/* Generated By:JJTree: Do not edit this line. ASTForInit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTForInit extends SimpleNode {
  public ASTForInit(int id) {
    super(id);
  }

  public ASTForInit(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b2a220d16a011d0584698f4bbfe4ed9 (do not edit this line) */
