/* Generated By:JJTree: Do not edit this line. ASTForCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

import java.io.PrintWriter;

public
class ASTForCondition extends SimpleNode {
  public ASTForCondition(int id) {
    super(id);
  }

  public ASTForCondition(JDCParser p, int id) {
    super(p, id);
  }

  public void process(PrintWriter ostr) {
    end=begin;
  }
}
/* JavaCC - OriginalChecksum=897725b7843bd0efaf6c0adb333d4d76 (do not edit this line) */
