/* Generated By:JJTree: Do not edit this line. ASTFieldDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

import java.io.PrintWriter;

public
class ASTFieldDeclaration extends SimpleNode implements Indentable {
  public ASTFieldDeclaration(int id) {
    super(id);
  }

  public ASTFieldDeclaration(JDCParser p, int id) {
    super(p, id);
  }

  public void process(PrintWriter ostr){
    super.process(ostr);

    ostr.print(";"); //final semicolon
  }
}
/* JavaCC - OriginalChecksum=03378efca1f710cf7e302781097563df (do not edit this line) */
