/* Generated By:JJTree: Do not edit this line. ASTFinally.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTFinally extends SimpleNode {
  public ASTFinally(int id) {
    super(id);
  }

  public ASTFinally(JDCParser p, int id) {
    super(p, id);
    indent = false; //don't indent further than try block
  }

}
/* JavaCC - OriginalChecksum=1694593774f27f96a589e9ece8f55e56 (do not edit this line) */
