/* Generated By:JJTree: Do not edit this line. ASTForBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTForBlock extends SimpleNode{
  public ASTForBlock(int id) {
    super(id);
  }

  public ASTForBlock(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=499ec2bc5c6b1a9fb9980c3e78fbd2d6 (do not edit this line) */
