/* Generated By:JJTree: Do not edit this line. ASTInclusiveOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTInclusiveOrExpression extends SimpleNode {
  public ASTInclusiveOrExpression(int id) {
    super(id);
  }

  public ASTInclusiveOrExpression(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c27fd4d7e1eb238fed1dccdcdf55520a (do not edit this line) */
