/* Generated By:JJTree: Do not edit this line. ASTInterfaceMemberDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTInterfaceMemberDeclaration extends SimpleNode {
  public ASTInterfaceMemberDeclaration(int id) {
    super(id);
  }

  public ASTInterfaceMemberDeclaration(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84939fa73682ff5ac62586a9c8a42155 (do not edit this line) */
