/* Generated By:JJTree: Do not edit this line. ASTIncrementDecrement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTIncrementDecrement extends SimpleNode {
  public ASTIncrementDecrement(int id) {
    super(id);
  }

  public ASTIncrementDecrement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=acf319068b5e4e60f170c0bcac98f21a (do not edit this line) */
