/* Generated By:JJTree: Do not edit this line. ASTImportDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTImportDeclaration extends SemicolonSimpleNode {
  public ASTImportDeclaration(int id) {
    super(id);
  }

  public ASTImportDeclaration(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e36ebc58777487409e65b7efb14ccc1d (do not edit this line) */
