/* Generated By:JJTree: Do not edit this line. ASTLocalVariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTLocalVariableDeclaration extends ASTStatementExpression {
  public ASTLocalVariableDeclaration(int id) {
    super(id);
  }

  public ASTLocalVariableDeclaration(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c5a11456f1c4985fb357c8b5f0c12a6 (do not edit this line) */
