/* Generated By:JJTree: Do not edit this line. ASTLabeledStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTLabeledStatement extends SimpleNode {
  public ASTLabeledStatement(int id) {
    super(id);
  }

  public ASTLabeledStatement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4d9ac282ce2ec5e2da2c63c929ec3481 (do not edit this line) */
