/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTMethodDeclarator extends SimpleNode {
  public ASTMethodDeclarator(int id) {
    super(id);
  }

  public ASTMethodDeclarator(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75336d1ddf5d2b7487cf17127d9167a5 (do not edit this line) */
