/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.JDCParser;

import java.io.PrintWriter;

public
class ASTMethodDeclaration extends SimpleNode implements Indentable {
    public ASTMethodDeclaration(int id) {
        super(id);
    }

    public ASTMethodDeclaration(JDCParser p, int id) {
        super(p, id);
    }

    public void process(PrintWriter ostr) {
        boolean isAbstract = false; //if the method is abstract it will end with a semicolon

        if (end.image.equals(";")) {
            isAbstract = true;
        }
        super.process(ostr);

        if (isAbstract) {
            ostr.print(";");
        }
    }
}
/* JavaCC - OriginalChecksum=13d6707ee18c3879af9de89ea775fb8f (do not edit this line) */
