/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationLookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTMethodDeclarationLookahead extends SimpleNode {
  public ASTMethodDeclarationLookahead(int id) {
    super(id);
  }

  public ASTMethodDeclarationLookahead(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=216ed0dc9032515833ed18712ce852d1 (do not edit this line) */
