/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTMultiplicativeOperator extends SimpleNode {
  public ASTMultiplicativeOperator(int id) {
    super(id);
  }

  public ASTMultiplicativeOperator(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d75e8099b9a18dd3a2619c50fcc87237 (do not edit this line) */
