/* Generated By:JJTree: Do not edit this line. ASTMinusSign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

import java.io.PrintWriter;

public
class ASTMinusSign extends SimpleNode {
  public ASTMinusSign(int id) {
    super(id);
  }

  public ASTMinusSign(JDCParser p, int id) {
    super(p, id);
  }

  public void process(PrintWriter ostr) {
    ostr.print(" -");
  }
}
/* JavaCC - OriginalChecksum=09f507692693d5bfff4c96ab50d97bce (do not edit this line) */
