/* Generated By:JJTree: Do not edit this line. ASTNestedInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTNestedInterfaceDeclaration extends SimpleNode {
  public ASTNestedInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTNestedInterfaceDeclaration(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eaf567466ea9c9574d2d0c116d1a18e9 (do not edit this line) */
