/* Generated By:JJTree: Do not edit this line. ASTNullLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTNullLiteral extends SimpleNode {
  public ASTNullLiteral(int id) {
    super(id);
  }

  public ASTNullLiteral(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=abab0ca3141f5e467f27509176e398cb (do not edit this line) */
