/* Generated By:JJTree: Do not edit this line. ASTNestedClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTNestedClassDeclaration extends SimpleNode {
  public ASTNestedClassDeclaration(int id) {
    super(id);
  }

  public ASTNestedClassDeclaration(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3e78bfae48bd45dc25826604ee059c1a (do not edit this line) */
