/* Generated By:JJTree: Do not edit this line. ASTNestedClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

import java.io.PrintWriter;

public
class ASTNestedClassDeclaration extends ClosingBraceSimpleNode implements Indentable {
  public ASTNestedClassDeclaration(int id) {
    super(id);
  }

  public ASTNestedClassDeclaration(JDCParser p, int id) {
    super(p, id);
  }

  public void process(PrintWriter ostr){
    //If it's a decaf class, make this nested class static, or it won't be usable from main
    if (isDecafClass()){
      begin.image = "static " + begin.image;
    }
    super.process(ostr);
  }
}
/* JavaCC - OriginalChecksum=60a998afc0a3b47314ec064e7392b409 (do not edit this line) */
