/* Generated By:JJTree: Do not edit this line. ASTPreIncrementExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTPreIncrementExpression extends SimpleNode {
  public ASTPreIncrementExpression(int id) {
    super(id);
  }

  public ASTPreIncrementExpression(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f9f59e730e53b58deb5ef969707f16d5 (do not edit this line) */
