/* Generated By:JJTree: Do not edit this line. ASTPreDecrementExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTPreDecrementExpression extends SimpleNode {
  public ASTPreDecrementExpression(int id) {
    super(id);
  }

  public ASTPreDecrementExpression(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=afaba5d1ece2be65312f9ba373c627de (do not edit this line) */
