/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTPrimarySuffix extends SimpleNode {
  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=88ecfaf5166c226ec56768b2f7fa8458 (do not edit this line) */
