/* Generated By:JJTree: Do not edit this line. ASTParensExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTParensExpression extends SimpleNode implements LastTokenEater {
  public ASTParensExpression(int id) {
    super(id);
  }

  public ASTParensExpression(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ebc1dfef74b95f950b84ba02a63e8de9 (do not edit this line) */
