/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffixIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTPrimarySuffixIdentifier extends SimpleNode implements LastTokenEater {
  public ASTPrimarySuffixIdentifier(int id) {
    super(id);
  }

  public ASTPrimarySuffixIdentifier(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a784663ba460c45feb629b33d736eb16 (do not edit this line) */
