/* Generated By:JJTree: Do not edit this line. ASTRelationalOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

public
class ASTRelationalOperator extends SimpleNode {
  public ASTRelationalOperator(int id) {
    super(id);
  }

  public ASTRelationalOperator(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8776ccc8f53423995f266124766ae9a4 (do not edit this line) */
