/* Generated By:JJTree: Do not edit this line. ASTsetFirstLastToken.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTsetFirstLastToken extends SimpleNode {
  public ASTsetFirstLastToken(int id) {
    super(id);
  }

  public ASTsetFirstLastToken(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1f18361e69d5289c91fded0aaf9e0ec (do not edit this line) */
