/* Generated By:JJTree: Do not edit this line. ASTSynchronizedStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTSynchronizedStatement extends SimpleNode {
  public ASTSynchronizedStatement(int id) {
    super(id);
  }

  public ASTSynchronizedStatement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a0eabf58b978b870c02efbf816f1d996 (do not edit this line) */
