/* Generated By:JJTree: Do not edit this line. ASTTry.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTTry extends SimpleNode {
  public ASTTry(int id) {
    super(id);
  }

  public ASTTry(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dfd8fea67a1ae62eee1656415cdadbb6 (do not edit this line) */
