/* Generated By:JJTree: Do not edit this line. ASTTernaryColon.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

import java.io.PrintWriter;

public
class ASTTernaryColon extends SimpleNode {
  public ASTTernaryColon(int id) {
    super(id);
  }

  public ASTTernaryColon(JDCParser p, int id) {
    super(p, id);
  }

  public void process(PrintWriter ostr) {
    ostr.print(" :");
  }
}
/* JavaCC - OriginalChecksum=26c1dc73f3dda28a243cc68966f2d8b5 (do not edit this line) */
