/* Generated By:JJTree: Do not edit this line. ASTTryStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTTryStatement extends SimpleNode {
  public ASTTryStatement(int id) {
    super(id);
  }

  public ASTTryStatement(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c54071491a641b01aa67a78e5ef64c73 (do not edit this line) */
