/* Generated By:JJTree: Do not edit this line. ASTTernaryQuestionMark.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

import java.io.PrintWriter;

public
class ASTTernaryQuestionMark extends SimpleNode {
  public ASTTernaryQuestionMark(int id) {
    super(id);
  }

  public ASTTernaryQuestionMark(JDCParser p, int id) {
    super(p, id);
  }

  public void process(PrintWriter ostr) {
    ostr.print(" ?");
  }

}
/* JavaCC - OriginalChecksum=56fcf557f4887bccce413ecaa8e23999 (do not edit this line) */
