/* Generated By:JJTree: Do not edit this line. ASTUnmodifiedInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTUnmodifiedInterfaceDeclaration extends SimpleNode {
  public ASTUnmodifiedInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTUnmodifiedInterfaceDeclaration(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ebdbfeaf213cf80266ed5020bccc3d1b (do not edit this line) */
