/* Generated By:JJTree: Do not edit this line. ASTUnmodifiedClassDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTUnmodifiedClassDeclaration extends SimpleNode {
  public ASTUnmodifiedClassDeclaration(int id) {
    super(id);
  }

  public ASTUnmodifiedClassDeclaration(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d9ab7a8ca6125ce355ab6a52279c70f6 (do not edit this line) */
