/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTVariableDeclarator extends SimpleNode {
  public ASTVariableDeclarator(int id) {
    super(id);
  }

  public ASTVariableDeclarator(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=acf869516133be21ee85f27bac2a1a40 (do not edit this line) */
