/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTVariableDeclaratorId extends SimpleNode {
  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8adbe896ae3dc2246dcee3f2d6b4b13c (do not edit this line) */
