/* Generated By:JJTree: Do not edit this line. ASTVariableInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

public
class ASTVariableInitializer extends SimpleNode {
  public ASTVariableInitializer(int id) {
    super(id);
  }

  public ASTVariableInitializer(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7e5b34968495bf4a5a47349130c1ca2d (do not edit this line) */
