/* Generated By:JJTree: Do not edit this line. ASTWhileAfterDo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.ast;

import main.java.parser.*;

import java.io.PrintWriter;

public
class ASTWhileAfterDo extends SimpleNode implements LastTokenEater, FinalSemicolonEater {
  public ASTWhileAfterDo(int id) {
    super(id);
  }

  public ASTWhileAfterDo(JDCParser p, int id) {
    super(p, id);
  }

  @Override
  public void process(PrintWriter ostr) {
    super.process(ostr);
    ostr.print(";"); //Manually print last semicolon
  }
}
/* JavaCC - OriginalChecksum=5bad422ec74a354f7e5227f28e0538c8 (do not edit this line) */
