/* Generated By:JJTree: Do not edit this line. ASTWhileAfterDo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

import parser.*;

import java.io.PrintWriter;

public
class ASTWhileAfterDo extends ConditionalSimpleNode implements LastTokenEater {
  public ASTWhileAfterDo(int id) {
    super(id);
  }

  public ASTWhileAfterDo(JDCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5bad422ec74a354f7e5227f28e0538c8 (do not edit this line) */
