/* Generated By:JavaCC: Do not edit this line. JDCParserTreeConstants.java Version 5.0 */
package main.java.ast;

import main.java.parser.*;

public interface JDCParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTPACKAGEDECLARATION = 2;
  public int JJTIMPORTDECLARATION = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTNESTEDCLASSDECLARATION = 5;
  public int JJTINTERFACEDECLARATION = 6;
  public int JJTFIELDDECLARATION = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTCONSTRUCTORDECLARATION = 9;
  public int JJTASSIGNMENT = 10;
  public int JJTCONDITIONALEXPRESSION = 11;
  public int JJTARGUMENTS = 12;
  public int JJTBLOCK = 13;
  public int JJTLOCALVARIABLEDECLARATION = 14;
  public int JJTSTATEMENTEXPRESSION = 15;
  public int JJTSWITCHSTATEMENT = 16;
  public int JJTCASESWITCHLABEL = 17;
  public int JJTDEFAULTSWITCHLABEL = 18;
  public int JJTIFSTATEMENT = 19;
  public int JJTELSESTATEMENT = 20;
  public int JJTWHILESTATEMENT = 21;
  public int JJTDOSTATEMENT = 22;
  public int JJTWHILEAFTERDO = 23;
  public int JJTFORBLOCK = 24;
  public int JJTFORSTATEMENT = 25;
  public int JJTBREAKSTATEMENT = 26;
  public int JJTRETURNSTATEMENT = 27;
  public int JJTCATCH = 28;
  public int JJTFINALLY = 29;
  public int JJTTRY = 30;
  public int JJTDECAFCLASS = 31;
  public int JJTDECAFMAIN = 32;
  public int JJTDECAFMETHOD = 33;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "PackageDeclaration",
    "ImportDeclaration",
    "ClassDeclaration",
    "NestedClassDeclaration",
    "InterfaceDeclaration",
    "FieldDeclaration",
    "MethodDeclaration",
    "ConstructorDeclaration",
    "Assignment",
    "ConditionalExpression",
    "Arguments",
    "Block",
    "LocalVariableDeclaration",
    "StatementExpression",
    "SwitchStatement",
    "CaseSwitchLabel",
    "DefaultSwitchLabel",
    "IfStatement",
    "ElseStatement",
    "WhileStatement",
    "DoStatement",
    "WhileAfterDo",
    "ForBlock",
    "ForStatement",
    "BreakStatement",
    "ReturnStatement",
    "Catch",
    "Finally",
    "Try",
    "DecafClass",
    "DecafMain",
    "DecafMethod",
  };
}
/* JavaCC - OriginalChecksum=bee29c3d4fdbd6285c2977ec9fa4cce1 (do not edit this line) */
