/* Generated By:JavaCC: Do not edit this line. JDCParserTreeConstants.java Version 5.0 */
package main.java.ast;

import main.java.parser.*;

public interface JDCParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTMETHODDECLARATION = 3;
  public int JJTCONDITIONALEXPRESSION = 4;
  public int JJTSINGLEEQUALS = 5;
  public int JJTBLOCK = 6;
  public int JJTLOCALVARIABLEDECLARATION = 7;
  public int JJTSTATEMENTEXPRESSION = 8;
  public int JJTSWITCHSTATEMENT = 9;
  public int JJTIFSTATEMENT = 10;
  public int JJTELSESTATEMENT = 11;
  public int JJTWHILESTATEMENT = 12;
  public int JJTDOSTATEMENT = 13;
  public int JJTFORBLOCK = 14;
  public int JJTFORSTATEMENT = 15;
  public int JJTRETURNSTATEMENT = 16;
  public int JJTDECAFCLASS = 17;
  public int JJTDECAFMAIN = 18;
  public int JJTDECAFMETHOD = 19;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "ClassDeclaration",
    "MethodDeclaration",
    "ConditionalExpression",
    "SingleEquals",
    "Block",
    "LocalVariableDeclaration",
    "StatementExpression",
    "SwitchStatement",
    "IfStatement",
    "ElseStatement",
    "WhileStatement",
    "DoStatement",
    "ForBlock",
    "ForStatement",
    "ReturnStatement",
    "DecafClass",
    "DecafMain",
    "DecafMethod",
  };
}
/* JavaCC - OriginalChecksum=ba4ebef321cf43fd9d9a6e1e3eb4dd08 (do not edit this line) */
