/* Generated By:JavaCC: Do not edit this line. JDCParserTreeConstants.java Version 5.0 */
package main.java.ast;

import main.java.parser.*;

public interface JDCParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTMETHODDECLARATION = 3;
  public int JJTCONDITIONALEXPRESSION = 4;
  public int JJTSINGLEEQUALS = 5;
  public int JJTBLOCK = 6;
  public int JJTLOCALVARIABLEDECLARATION = 7;
  public int JJTSTATEMENTEXPRESSION = 8;
  public int JJTIFSTATEMENT = 9;
  public int JJTWHILESTATEMENT = 10;
  public int JJTDOSTATEMENT = 11;
  public int JJTFORSTATEMENT = 12;
  public int JJTDECAFBLOCK = 13;
  public int JJTDECAFMETHOD = 14;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "ClassDeclaration",
    "MethodDeclaration",
    "ConditionalExpression",
    "SingleEquals",
    "Block",
    "LocalVariableDeclaration",
    "StatementExpression",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "DecafBlock",
    "DecafMethod",
  };
}
/* JavaCC - OriginalChecksum=e16ef78b2213ffb9fc6cc23ae26684db (do not edit this line) */
